keys:
  - &ghrunner age1tktsvp8hdy0kt0wnxyh5uj2nxlqq9kvsdqcym8085w7hrs8lvu8q7lcnp6
  - &noteed age1jydee60ssqkgd2uayarrar7ndudst4ey2mpm580n0vkswkea7v5sawgmxj
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *ghrunner
          - *noteed
